modLoader="javafml"
license="MIT"
loaderVersion="[35,)"

[[mods]]
modId="spawn"
version="1.0.0"
displayName="Spawn"
logoFile="pack.png"
credits="yurisuika"
authors="yurisuika"
description="Spawn - spawn in The Sky."

[[dependencies.spawn]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.spawn]]
modId="sky"
mandatory=true
versionRange="[1.2.2,)"
ordering="NONE"
side="BOTH"